name: pyradiosky
channels:
  - conda-forge
dependencies:
  - astropy>=6.0
  - astropy-healpix>=1.0.2
  - astroquery>=0.4.4
  - h5py>=3.7
  - matplotlib
  - numpy>=1.23
  - coverage
  - pip
  - pre-commit
  - pypandoc
  - pytest-cov
  - pyuvdata>=3.1.0
  - scipy>=1.9
  - setuptools_scm>=8.1
  - sphinx
  - pip:
      - lunarsky>=0.2.5
