name: pyradiosky
channels:
  - conda-forge
  - defaults
dependencies:
  - astropy>=5.0.4
  - astropy-healpix
  - astroquery
  - h5py
  - numpy
  - coverage
  - pip
  - pre-commit
  - pypandoc
  - pytest-cov
  - pyuvdata>=2.2.10
  - pyyaml
  - scipy
  - setuptools_scm
  - sphinx
  - pip:
      - lunarsky
