name: pyradiosky
channels:
  - conda-forge
  - defaults
dependencies:
  - astropy
  - astropy-healpix
  - numpy
  - pyyaml
  - scipy
  - coverage
  - pytest-cov
  - setuptools_scm
  - pip
  - pip:
      - flake8-docstrings
      - flake8-pytest
      - flake8-black
