name: pyradiosky
channels:
  - conda-forge
dependencies:
  - astropy>=5.2
  - astropy-healpix>=0.6
  - astroquery>=0.4.4
  - h5py>=3.0
  - matplotlib
  - numpy>=1.20
  - coverage
  - pip
  - pre-commit
  - pypandoc
  - pytest-cov
  - pyuvdata>=2.4.1
  - pyyaml
  - scipy>=1.5
  - setuptools_scm>=7.0.3
  - sphinx
  - pip:
      - lunarsky>=0.2.1
