name: pyradiosky
channels:
  - conda-forge
dependencies:
  - astropy>=6.0
  - astropy-healpix>=1.0.2
  - astroquery>=0.4.4
  - h5py>=3.4
  - matplotlib
  - numpy>=1.23
  - coverage
  - pip
  - pre-commit
  - pypandoc
  - pytest-cov
  - pyuvdata>=2.4.3
  - scipy>=1.7.3
  - setuptools>=61
  - setuptools_scm>=7.0.3
  - sphinx
  - pip:
      - lunarsky>=0.2.1
